# Generated by Django 3.2.12 on 2023-08-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.TextField()),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('model', models.TextField()),
                ('colorway', models.TextField()),
                ('image', models.TextField()),
                ('size', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('retail_price', models.TextField()),
                ('last_sold_price', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
