# Generated by Django 3.2.12 on 2023-08-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoe',
            table='shoes',
        ),
    ]
