# Generated by Django 3.2.12 on 2023-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_api', '0002_alter_shoe_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='link',
            field=models.TextField(default='/error'),
            preserve_default=False,
        ),
    ]
