# Generated by Django 3.2.12 on 2023-08-07 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneaker_api', '0003_shoe_link'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoe',
            table=None,
        ),
    ]
